version: 2

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

formats: []

python:
   version: 3.8
   install:
      - requirements: requirements.txt
      - requirements: docs/requirements.txt
