name: CI

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Python 3.10
            python: "3.10.5"
            toxenv: py310

          - name: Code style checks
            python: "3.10.5"
            toxenv: codestyle

          - name: Documentation build
            python: "3.10.5"
            toxenv: build_docs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
