name: 📦 Build and Publish

on:
  push:
    tags:
      - v[0-9].*


jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        shell: bash -l {0}
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish package to PyPI
        if: github.repository == 'theXYZT/pulsarbat'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
