name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Test on Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pwd

      - name: Lint with flake8
        run: |
          flake8 pulsarbat tests --show-source --statistics

      - name: Testing and Coverage
        run: |
          pytest --cov-report=xml --cov=pulsarbat

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
