name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Testing and coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov-report=xml --cov=pulsarbat

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
